name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: Detekt
        run: ./gradlew detekt

      - name: Run All Tests
        run: ./gradlew test
